ALTER TABLE users DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public access" ON users;
DROP POLICY IF EXISTS "Public read access" ON users;
DROP POLICY IF EXISTS "Users can view their own data" ON users;
DROP POLICY IF EXISTS "Users can update their own data" ON users;
DROP POLICY IF EXISTS "Admins can view all users" ON users;
DROP POLICY IF EXISTS "Admins can update all users" ON users;
DROP POLICY IF EXISTS "Admins can manage all users" ON users;
DROP POLICY IF EXISTS "Allow public read access" ON users;
DROP POLICY IF EXISTS "Allow users to update own data" ON users;
DROP POLICY IF EXISTS "Allow admins to insert" ON users;
DROP POLICY IF EXISTS "Allow admins to delete" ON users;
DROP POLICY IF EXISTS "users_read_policy" ON users;
DROP POLICY IF EXISTS "users_update_own_policy" ON users;
DROP POLICY IF EXISTS "admin_all_operations_policy" ON users;
DROP POLICY IF EXISTS "allow_select" ON users;
DROP POLICY IF EXISTS "allow_insert" ON users;
DROP POLICY IF EXISTS "allow_update" ON users;
DROP POLICY IF EXISTS "allow_delete" ON users;
DROP POLICY IF EXISTS "simple_select_policy" ON users;
DROP POLICY IF EXISTS "simple_insert_policy" ON users;
DROP POLICY IF EXISTS "simple_update_policy" ON users;
DROP POLICY IF EXISTS "simple_delete_policy" ON users;
CREATE POLICY "simple_select_policy" ON users FOR SELECT USING (true);
CREATE POLICY "simple_insert_policy" ON users FOR INSERT WITH CHECK (true);
CREATE POLICY "simple_update_policy" ON users FOR UPDATE USING (true);
CREATE POLICY "simple_delete_policy" ON users FOR DELETE USING (true);
ALTER TABLE users ENABLE ROW LEVEL SECURITY;